[tool.ruff]
line-length = 100
target-version = "py39"
exclude = ["docs/curation/*"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
exclude = ["^docs/curation/"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
